### PR TITLE
Set up Dependabot for go dependencies and github actions

### PR DESCRIPTION
**Pull request by mmorel-35**

### CODE REVIEW

**Review by shaneutt — APPROVED** [review]
Forgot about it! Thanks @mmorel-35 :bow:

**Comment by shaneutt** [comment]
@mmorel-35 looks like we need the CLA signed for this repository and then we're :heavy_check_mark:

**Comment by mmorel-35** [comment]
It's weird, I haven't received anything from license/cla to sign as I usually do

**Comment by shaneutt** [comment]
> It's weird, I haven't received anything from license/cla to sign as I usually do

:thinking: ok I'll check on this, thanks for the heads up

**Pull request merged**
